using System.Linq;
using System.Collections.Generic;
using SFS.Parts;
using SFS.World;
using SFS.Builds;
using SFS.Parts.Modules;
using HarmonyLib;

namespace StagesExpanded.Simulation
{
    public abstract class SimulationInput
    {
        public abstract JointGroup GetJointGroup();
        public abstract List<Stage> GetStages();
        public abstract double GetThrottle();
        public abstract bool RunSimulation();
        public abstract bool ResetWindowUI(SimulationInput previousInput);
    }

    public class WorldInput : SimulationInput
    {
        public Rocket Rocket { get; private set; }

        public WorldInput(Rocket rocket)
        {
            Rocket = rocket;
        }

        public override JointGroup GetJointGroup()
        {
            return Rocket.jointsGroup.ShallowCopy();
        }

        public override List<Stage> GetStages()
        {
            return Rocket.staging.stages;
        }

        public override double GetThrottle()
        {
            if (Rocket.throttle.throttlePercent.Value > 0.001)
                return Rocket.throttle.throttlePercent.Value;
            else
                return 1;
        }

        public override bool RunSimulation()
        {
            if (SandboxSettings.main.settings.infiniteFuel)
                return false;
            else if (Rocket == null)
                return false;
            else if (!Rocket.hasControl)
                return false;
            else
                return true;
        }

        public override bool ResetWindowUI(SimulationInput previousInput)
        {
            if (previousInput is WorldInput input && Rocket == input.Rocket)
            {
                return false;
            }
            return true;
        }
    }

    public class BuildInput : SimulationInput
    {
        private PartHolder PartHolder => BuildManager.main.buildGrid.activeGrid.partsHolder;
        // * Set by the `BuildState_Clear` patch.
        public static bool GridCleared { get; set; }

        public override JointGroup GetJointGroup()
        {
            JointGroup joints = new JointGroup
            (
                RocketManager.GenerateJoints(PartHolder.GetArray()),
                PartHolder.parts
            );

            // * Need to generate fuel flows since they aren't generated by the game in the build scene.
            foreach (FlowModule module in PartHolder.parts.GetModules<FlowModule>())
            {
                Part part = module.transform.GetComponentInParentTree<Part>();
                foreach (FlowModule.Flow flow in module.sources)
                {
                    flow.sources = flow.GetSources_Simulation(joints, part);
                    foreach (ResourceModule rm in flow.sources)
                    {
                        rm.flowModules.Add(flow);
                    }
                }
            }

            return joints;
        }

        public override List<Stage> GetStages()
        {
            return BuildManager.main.buildMenus.staging.stages;
        }

        public override double GetThrottle()
        {
            return 1;
        }

        public override bool RunSimulation()
        {
            return GetStages().Count > 0 || PartHolder.GetModules<EngineModule>().Any(em => em.engineOn.Value);
        }

        public override bool ResetWindowUI(SimulationInput previousInput)
        {
            if (previousInput is BuildInput && !GridCleared)
            {
                return false;
            }
            GridCleared = false;
            return true;
        }
    }
}