using System.Linq;
using System.Collections.Generic;
using SFS.Parts;
using SFS.World;
using SFS.Builds;
using SFS.Parts.Modules;

namespace StagesExpanded.Simulation
{
    public abstract class SimulationInput
    {
        public abstract JointGroup GetJointGroup(bool forSimulation);
        public abstract List<Stage> GetStages(JointGroup group);
        public abstract double GetThrottle();
        public abstract bool RunSimulation();
        public abstract bool ResetWindowUI(SimulationInput previousInput);
    }

    public class WorldInput : SimulationInput
    {
        public Rocket Rocket { get; }

        public WorldInput(Rocket rocket)
        {
            Rocket = rocket;
        }

        public override JointGroup GetJointGroup(bool forSimulation)
        {
            return Rocket.jointsGroup.ShallowCopy();
        }

        public override List<Stage> GetStages(JointGroup group)
        {
            return Rocket.staging.stages.Copy();
        }

        public override double GetThrottle()
        {
            if (Rocket.throttle.throttlePercent.Value > 0.001)
                return Rocket.throttle.throttlePercent.Value;
            else
                return 1;
        }

        public override bool RunSimulation()
        {
            if (SandboxSettings.main.settings.infiniteFuel)
                return false;
            else if (Rocket == null)
                return false;
            else if (!Rocket.hasControl)
                return false;
            else
                return true;
        }

        public override bool ResetWindowUI(SimulationInput previousInput)
        {
            return !(previousInput is WorldInput input) || Rocket != input.Rocket;
        }
    }

    public class BuildInput : SimulationInput
    {
        private static PartHolder PartHolder => BuildManager.main.buildGrid.activeGrid.partsHolder;
        // * Set by the `BuildState_Clear` patch.
        public static bool GridCleared { get; set; }

        public override JointGroup GetJointGroup(bool forSimulation)
        {
            new JointGroup
            (
                RocketManager.GenerateJoints(PartHolder.GetArray()),
                PartHolder.parts
            ).RecreateGroups(out List<JointGroup> newGroups);


            JointGroup joints = newGroups.FirstOrDefault(jg => jg.parts.GetModules<ControlModule>().Any(cm => cm.hasControl.Value));
            
            if (joints == null)
                return null;

            if (forSimulation)
            {
                // * Need to generate fuel flows since they aren't generated by the game in the build scene.
                foreach (FlowModule module in joints.parts.GetModules<FlowModule>())
                {
                    Part part = module.transform.GetComponentInParentTree<Part>();
                    foreach (FlowModule.Flow flow in module.sources)
                    {
                        flow.sources = flow.GetSources_Simulation(joints, part);
                        foreach (ResourceModule rm in flow.sources)
                        {
                            rm.flowModules.Add(flow);
                        }
                    }
                }
            }

            return joints;
        }

        public override List<Stage> GetStages(JointGroup group)
        {
            List<Stage> stages = BuildManager.main.buildMenus.staging.stages.Copy();
            foreach (Stage stage in stages)
            {
                stage.parts.RemoveAll(p => !group.dictionary.ContainsKey(p));
            }
            stages.RemoveAll(s => s.PartCount == 0);
            return stages;
        }

        public override double GetThrottle()
        {
            return 1;
        }

        public override bool RunSimulation()
        {
            JointGroup group = GetJointGroup(false);
            if (group == null)
                return false;
            return GetStages(group).Count > 0 || group.parts.GetModules<EngineModule>().Any(em => em.engineOn.Value);
        }

        public override bool ResetWindowUI(SimulationInput previousInput)
        {
            if (previousInput is BuildInput && !GridCleared)
            {
                return false;
            }
            GridCleared = false;
            return true;
        }
    }
}